# Generated by Django 3.1.7 on 2021-04-21 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20210420_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='artist',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
