# Generated by Django 3.1.7 on 2021-04-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210421_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
